- name: install haproxy
  yum: name=haproxy state=present

- name: configure haproxy.cfg
  template:
    src: templates/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: configure rsyslog
  template:
    src: templates/rsyslog.conf
    dest: /etc/rsyslog.conf
  notify: restart rsyslog 

- name: start haproxy
  service: name=haproxy state=started enabled=yes
