- name: install openssl
  yum: name={{ item }} state=present
  with_items:
    - openssl

- name: check Self-signed certificate
  stat: path=~/{{ inventory_hostname}}.crt
  register: is_sscert


- name: create Self-signed certificate
  command: openssl req -batch -new -x509 -newkey rsa:2048 -nodes -sha256 -subj /CN={{ ansible_fqdn }}/O=self -days 3650 -keyout ~/{{ inventory_hostname }}.key -out ~/{{ inventory_hostname }}.crt
  when:
    - is_sscert.stat.exists==False
