- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: install base
  yum: name={{ item }} state=present
  with_items:
    - wget
    - unzip
    - git

- name: configure selinux permissive 
  selinux: policy=targeted state=permissive


